language: python
services:
  - postgresql
  - redis-server
python:
  - "2.7"
before_script:
- export DATABASE_URL=postgres://postgres@localhost/providers
- export DJANGO_SECRET=`openssl rand -base64 32`
- psql -c 'CREATE DATABASE "providers";' -U postgres
install:
  - "pip install -r requirements/test.txt"
script:
  - ./providers/manage.py test providers
after_success:
  - coveralls

deploy:
  provider: heroku
  app:
    master: providers-dev
    qa: providers-qa
    prod: providers-prod
  on:
    repo: kamotos/mozio-providers
  run:
    - "./providers/manage.py migrate"

notifications:
  email: false

# This reportedly works around an issue downloading packages from pypi on
# travis. Consider removing this after the underlying issue is fixed.
# https://github.com/travis-ci/travis-ci/issues/2389
sudo: false

matrix:
  fast_finish: true
