# App
web:
  extends:
    file: app.yml
    service: app
  dockerfile: ./docker/Dockerfile-production
  command: gunicorn config.wsgi:application -b 0.0.0.0:3060
  environment:
   - REQUIREMENTS_FILE=production.txt
   - DJANGO_SETTINGS_MODULE=config.settings.production
  links:
   - db
   - worker
   - redis
  ports:
   - "3060:3060"

db:
  image: postgres
  volumes:
   - /opt/mozio/postgres:/var/lib/postgresql/data

redis:
  image: redis
  volumes:
    - /opt/mozio/redis/data:/data