# App
web:
  extends:
    file: app.yml
    service: app
  dockerfile: ./docker/Dockerfile-production
  env_file: .env
  command:  gunicorn providers.wsgi:application -b 0.0.0.0:3060  --pythonpath ./providers
  environment:
   - DJANGO_CONFIGURATION=Production
  links:
   - geodb
   - redis
  ports:
   - "3060:3060"

geodb:
  image: mdillon/postgis
  volumes:
   - /opt/mozio/postgis/data:/var/lib/postgresql/data

redis:
  image: redis
  volumes:
    - /opt/mozio/redis/data:/data