# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_areas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Price'),
        ),
    ]
